#lsp to minirgbd
#python train_human.py '/data/AmitRoyChowdhury/dripta/lsp' '/data/AmitRoyChowdhury/MINI-RGBD_web' -s LSP -t MiniRGBD --target-train MiniRGBD_mt --log logs/lsp2mini_exp/real2syn --debug --lambda_c 1 --pretrain-epoch 40  --rotation_stu 60 --shear_stu -30 30 --translate_stu 0.05 0.05 --scale_stu 0.6 1.3 --color_stu 0.25 --blur_stu 0 --rotation_tea 60 --shear_tea -30 30 --translate_tea 0.05 0.05 --scale_tea 0.6 1.3 --color_tea 0.25 --blur_tea 0 -b 32 --mask-ratio 0.5 --k 1 --s2t-freq 0.5 --s2t-alpha 0 1 --t2s-freq 0.5 --t2s-alpha 0 1 --occlude-rate 0.5 --occlude-thresh 0.9
#surreal to minirgbd
#python train_human.py '/data/AmitRoyChowdhury/dripta/surreal_processed' '/data/AmitRoyChowdhury/MINI-RGBD_web' -s SURREAL -t MiniRGBD --target-train MiniRGBD_mt --log logs/surreal2mini_dless_exp/syn2syn_corr --debug --lambda_c 1 --pretrain-epoch 40 --rotation_stu 60 --shear_stu -30 30 --translate_stu 0.05 0.05 --scale_stu 0.6 1.3 --color_stu 0.25 --blur_stu 0 --rotation_tea 60 --shear_tea -30 30 --translate_tea 0.05 0.05 --scale_tea 0.6 1.3 --color_tea 0.25 --blur_tea 0 -b 32 --mask-ratio 0.5 --k 1 --decoder-name './adain/logs/surreal2mrgbd_0_1/saved_model/decoder_surreal2mrgbd_0_1.pth.tar' --s2t-freq 0.5 --s2t-alpha 0 1 --t2s-freq 0.5 --t2s-alpha 0 1 --occlude-rate 0.5 --occlude-thresh 0.9 
#surreal to minirgbd without style decoder
#python train_human.py '/data/AmitRoyChowdhury/dripta/surreal_processed' '/data/AmitRoyChowdhury/MINI-RGBD_web' -s SURREAL -t MiniRGBD --target-train MiniRGBD_mt --log logs/surreal2mini_dless_exp2/syn2syn_corr --debug --lambda_c 1 --pretrain-epoch 40 --rotation_stu 60 --shear_stu -30 30 --translate_stu 0.05 0.05 --scale_stu 0.6 1.3 --color_stu 0.25 --blur_stu 0 --rotation_tea 60 --shear_tea -30 30 --translate_tea 0.05 0.05 --scale_tea 0.6 1.3 --color_tea 0.25 --blur_tea 0 -b 32 --mask-ratio 0.5 --k 1 --s2t-freq 0.5 --s2t-alpha 0 1 --t2s-freq 0.5 --t2s-alpha 0 1 --occlude-rate 0.5 --occlude-thresh 0.9 
#surreal to minirgbd without style decoder and with visibility aware loss
#python train_human_vis_loss.py '/data/AmitRoyChowdhury/dripta/surreal_processed' '/data/AmitRoyChowdhury/MINI-RGBD_web' -s SURREAL -t MiniRGBD --target-train MiniRGBD_mt --log logs/surreal2mini_styleless_visloss_exp3/syn2syn --debug --lambda_c 1 --pretrain-epoch 40 --rotation_stu 60 --shear_stu -30 30 --translate_stu 0.05 0.05 --scale_stu 0.6 1.3 --color_stu 0.25 --blur_stu 0 --rotation_tea 60 --shear_tea -30 30 --translate_tea 0.05 0.05 --scale_tea 0.6 1.3 --color_tea 0.25 --blur_tea 0 -b 32 --mask-ratio 0.5 --k 1 --s2t-freq 0.5 --s2t-alpha 0 1 --t2s-freq 0.5 --t2s-alpha 0 1 --occlude-rate 0.5 --occlude-thresh 0.9
#surreal to minirgbd without style decoder, with visibility aware loss and SFDA
#python train_human_SFDA.py '/data/AmitRoyChowdhury/dripta/surreal_processed' '/data/AmitRoyChowdhury/MINI-RGBD_web' -s SURREAL -t MiniRGBD --target-train MiniRGBD_mt --log logs/surreal2mini_SFDA/syn2syn --debug --lambda_c 1 --pretrain-epoch 40 --rotation_stu 60 --shear_stu -30 30 --translate_stu 0.05 0.05 --scale_stu 0.6 1.3 --color_stu 0.25 --blur_stu 0 --rotation_tea 60 --shear_tea -30 30 --translate_tea 0.05 0.05 --scale_tea 0.6 1.3 --color_tea 0.25 --blur_tea 0 -b 32 --mask-ratio 0.5 --k 1 --s2t-freq 0.5 --s2t-alpha 0 1 --t2s-freq 0.5 --t2s-alpha 0 1 --occlude-rate 0.5 --occlude-thresh 0.9
#surreal to minirgbd without style decoder, with visibility aware loss and with prior
python train_human_to_infant.py '/data/AmitRoyChowdhury/dripta/surreal_processed' '/data/AmitRoyChowdhury/MINI-RGBD_web' -s SURREAL -t MiniRGBD --target-train MiniRGBD_mt --log logs/surreal2mini_Final/syn2syn --prior '/data/AmitRoyChowdhury/sarosij/prior_data/ckpts/prior_stage_3.pt' --debug --lambda_c 1 --lambda_p 1e-6 --pretrain-epoch 40 --rotation_stu 60 --shear_stu -30 30 --translate_stu 0.05 0.05 --scale_stu 0.6 1.3 --color_stu 0.25 --blur_stu 0 --rotation_tea 60 --shear_tea -30 30 --translate_tea 0.05 0.05 --scale_tea 0.6 1.3 --color_tea 0.25 --blur_tea 0 -b 32 --mask-ratio 0.5 --k 1 --s2t-freq 0.5 --s2t-alpha 0 1 --t2s-freq 0.5 --t2s-alpha 0 1 --occlude-rate 0.5 --occlude-thresh 0.9
