#MINIRGBD EXPTS
#surreal to minirgbd
#python train_human.py '/data/AmitRoyChowdhury/dripta/surreal_processed' '/data/AmitRoyChowdhury/MINI-RGBD_web' -s SURREAL -t MiniRGBD --target-train MiniRGBD_mt --log logs/surreal2mini_dless_exp/syn2syn_corr --debug --lambda_c 1 --pretrain-epoch 40 --rotation_stu 60 --shear_stu -30 30 --translate_stu 0.05 0.05 --scale_stu 0.6 1.3 --color_stu 0.25 --blur_stu 0 --rotation_tea 60 --shear_tea -30 30 --translate_tea 0.05 0.05 --scale_tea 0.6 1.3 --color_tea 0.25 --blur_tea 0 -b 32 --mask-ratio 0.5 --k 1 --decoder-name './adain/logs/surreal2mrgbd_0_1/saved_model/decoder_surreal2mrgbd_0_1.pth.tar' --s2t-freq 0.5 --s2t-alpha 0 1 --t2s-freq 0.5 --t2s-alpha 0 1 --occlude-rate 0.5 --occlude-thresh 0.9 
#surreal to minirgbd without style decoder
#python train_human.py '/data/AmitRoyChowdhury/dripta/surreal_processed' '/data/AmitRoyChowdhury/MINI-RGBD_web' -s SURREAL -t MiniRGBD --target-train MiniRGBD_mt --log logs/surreal2mini_dless_exp2/syn2syn_corr --debug --lambda_c 1 --pretrain-epoch 40 --rotation_stu 60 --shear_stu -30 30 --translate_stu 0.05 0.05 --scale_stu 0.6 1.3 --color_stu 0.25 --blur_stu 0 --rotation_tea 60 --shear_tea -30 30 --translate_tea 0.05 0.05 --scale_tea 0.6 1.3 --color_tea 0.25 --blur_tea 0 -b 32 --mask-ratio 0.5 --k 1 --s2t-freq 0.5 --s2t-alpha 0 1 --t2s-freq 0.5 --t2s-alpha 0 1 --occlude-rate 0.5 --occlude-thresh 0.9 
#surreal to minirgbd without style decoder, with visibility and with task agnostic prior (from checkpoint)
#python train_human_to_infant.py '/data/AmitRoyChowdhury/dripta/surreal_processed' '/data/AmitRoyChowdhury/MINI-RGBD_web' -s SURREAL -t MiniRGBD --target-train MiniRGBD_mt --log logs/surreal2mini_ta_prior/real2syn --prior '/data/AmitRoyChowdhury/sarosij/prior_data/SyRIP/ckpts/all/prior_stage_3.pt' --resume 'checkpoints/surreal2mini_1/syn2syn_pose_resnet101/checkpoints_2024-06-09-00_17_17/best.pth' --debug --lambda_c 1 --lambda_s 1e-6 --lambda_p 1e-6 --mode 'prior' --rotation_stu 60 --shear_stu -30 30 --translate_stu 0.05 0.05 --scale_stu 0.6 1.3 --color_stu 0.25 --blur_stu 0 --rotation_tea 60 --shear_tea -30 30 --translate_tea 0.05 0.05 --scale_tea 0.6 1.3 --color_tea 0.25 --blur_tea 0 -b 32 --mask-ratio 0.5 --k 1 --s2t-freq 0.5 --s2t-alpha 0 1 --t2s-freq 0.5 --t2s-alpha 0 1 --occlude-rate 0.5 --occlude-thresh 0.9
#surreal to minirgbd without style decoder, with visibility, with kp encoder and with prior (from checkpoint)
#python train_human_to_infant.py '/data/AmitRoyChowdhury/dripta/surreal_processed' '/data/AmitRoyChowdhury/MINI-RGBD_web' -s SURREAL -t MiniRGBD --target-train MiniRGBD_mt --log logs/surreal2mini_ta_prior_ft/syn2syn --prior '/data/AmitRoyChowdhury/sarosij/prior_data/SyRIP/ckpts/all/ft_prior_stage_3.pt' --kp2seg '/data/AmitRoyChowdhury/sarosij/kp2seg_data/SURREAL_kp2seg_gan.pt' --pretrain 'checkpoints/surreal2mini_ta_all/syn2syn_pose_resnet101/checkpoints_2024-07-03-10_48_14/best_pt.pth' --debug --lambda_c 1 --lambda_s 1e-6 --lambda_p 1e-6 --mode 'prior' --rotation_stu 60 --shear_stu -30 30 --translate_stu 0.05 0.05 --scale_stu 0.6 1.3 --color_stu 0.25 --blur_stu 0 --rotation_tea 60 --shear_tea -30 30 --translate_tea 0.05 0.05 --scale_tea 0.6 1.3 --color_tea 0.25 --blur_tea 0 -b 32 --mask-ratio 0.5 --k 1 --s2t-freq 0.5 --s2t-alpha 0 1 --t2s-freq 0.5 --t2s-alpha 0 1 --occlude-rate 0.5 --occlude-thresh 0.9
#surreal to minirgbd without style decoder, with visibility, with kp encoder and with prior
#python train_human_to_infant.py '/data/AmitRoyChowdhury/dripta/surreal_processed' '/data/AmitRoyChowdhury/MINI-RGBD_web' -s SURREAL -t MiniRGBD --target-train MiniRGBD_mt --log logs/check/regda --prior '/data/AmitRoyChowdhury/sarosij/prior_data/SyRIP/ckpts/all/ft_prior_stage_3.pt' --kp2seg '/data/AmitRoyChowdhury/sarosij/kp2seg_data/SURREAL_kp2seg_gan.pt' --pretrain 'checkpoints/surreal2mini_ta_all/syn2syn_pose_resnet101/checkpoints_2024-07-03-10_48_14/best_pt.pth' --debug --lambda_c 1 --lambda_s 1e-6 --lambda_p 1e-6 --mode 'all' --rotation_stu 60 --shear_stu -30 30 --translate_stu 0.05 0.05 --scale_stu 0.6 1.3 --color_stu 0.25 --blur_stu 0 --rotation_tea 60 --shear_tea -30 30 --translate_tea 0.05 0.05 --scale_tea 0.6 1.3 --color_tea 0.25 --blur_tea 0 -b 32 --mask-ratio 0.5 --k 1 --s2t-freq 0.5 --s2t-alpha 0 1 --t2s-freq 0.5 --t2s-alpha 0 1 --occlude-rate 0.5 --occlude-thresh 0.9
#MiniRGBD to MiniRGBD (Oracle)
#python train_human_to_infant.py '/data/AmitRoyChowdhury/MINI-RGBD_web' '/data/AmitRoyChowdhury/MINI-RGBD_web' -s MiniRGBD -t MiniRGBD --target-train MiniRGBD_mt --log logs/mini2mini_oracle/syn2syn --debug --lambda_c 1 --pretrain-epoch 40 --mode 'oracle'

#lsp to minirgbd without style decoder, with visibility, with kp encoder and with prior (PRDA)
#python train_human_to_infant.py '/data/AmitRoyChowdhury/dripta/lsp' '/data/AmitRoyChowdhury/MINI-RGBD_web' -s LSP -t MiniRGBD --target-train MiniRGBD_mt --log logs/lsp2mini/real2syn --prior '/data/AmitRoyChowdhury/sarosij/prior_data/MiniRGBD/ckpts/prior_stage_3.pt' --kp2seg '/data/AmitRoyChowdhury/sarosij/kp2seg_data/SURREAL_kp2seg_gan.pt' --debug --lambda_c 1 --pretrain-epoch 40 --lambda_s 1e-6 --lambda_p 1e-6 --mode 'all' --rotation_stu 60 --shear_stu -30 30 --translate_stu 0.05 0.05 --scale_stu 0.6 1.3 --color_stu 0.25 --blur_stu 0 --rotation_tea 60 --shear_tea -30 30 --translate_tea 0.05 0.05 --scale_tea 0.6 1.3 --color_tea 0.25 --blur_tea 0 -b 32 --mask-ratio 0.5 --k 1 --s2t-freq 0.5 --s2t-alpha 0 1 --t2s-freq 0.5 --t2s-alpha 0 1 --occlude-rate 0.5 --occlude-thresh 0.9

#SYRIP EXPTS
#syrip to syrip (Oracle)
#python train_human_to_infant.py '/data/AmitRoyChowdhury/SyRIP/data/syrip/images' '/data/AmitRoyChowdhury/SyRIP/data/syrip/images' -s SyRIP -t SyRIP --target-train SyRIP_mt --log logs/sp2sp_oracle1/syn2syn --debug --lambda_c 1 --pretrain-epoch 40 --mode 'oracle'
#surreal to syrip without style decoder (Baseline - from checkpoint)
#python train_human_to_infant.py '/data/AmitRoyChowdhury/dripta/surreal_processed' '/data/AmitRoyChowdhury/SyRIP/data/syrip/images' -s SURREAL -t SyRIP --target-train SyRIP_mt --log logs/sp2sp_baseline/syn2mix --resume 'checkpoints/surreal2s/syn2syn_pose_resnet101/checkpoints_2024-06-19-12_49_21/best_pt.pth' --debug --lambda_c 1 --pretrain-epoch 0 --mode 'baseline' --rotation_stu 60 --shear_stu -30 30 --translate_stu 0.05 0.05 --scale_stu 0.6 1.3 --color_stu 0.25 --blur_stu 0 --rotation_tea 60 --shear_tea -30 30 --translate_tea 0.05 0.05 --scale_tea 0.6 1.3 --color_tea 0.25 --blur_tea 0 -b 32 --mask-ratio 0.5 --k 1 --s2t-freq 0.5 --s2t-alpha 0 1 --t2s-freq 0.5 --t2s-alpha 0 1 --occlude-rate 0.5 --occlude-thresh 0.9 
#surreal to syrip without style decoder and with prior (from checkpoint)
#All prior: /data/AmitRoyChowdhury/sarosij/prior_data/SyRIP/ckpts/all/prior_stage_3.pt
#real-syn prior: /data/AmitRoyChowdhury/SyRIP/SyRIP_data_split/300S/prior/prior_stage_3.pt
#python train_human_to_infant.py '/data/AmitRoyChowdhury/dripta/surreal_processed' '/data/AmitRoyChowdhury/SyRIP/data/syrip/images' -s SURREAL -t SyRIP --target-train SyRIP_mt --log logs/surreal2sp_ablation/threshold_0.9 --prior '/data/AmitRoyChowdhury/sarosij/prior_data/MiniRGBD/ckpts/prior_stage_3.pt' --kp2seg '/data/AmitRoyChowdhury/sarosij/kp2seg_data/SURREAL_kp2seg_gan.pt' --pretrain 'checkpoints/surreal2mini_ta_all/syn2syn_pose_resnet101/checkpoints_2024-07-03-10_48_14/best_pt.pth' --debug --lambda_c 1 --lambda_s 1e-6 --lambda_p 1e-6 --mode 'all' --rotation_stu 60 --shear_stu -30 30 --translate_stu 0.05 0.05 --scale_stu 0.6 1.3 --color_stu 0.25 --blur_stu 0 --rotation_tea 60 --shear_tea -30 30 --translate_tea 0.05 0.05 --scale_tea 0.6 1.3 --color_tea 0.25 --blur_tea 0 -b 32 --mask-ratio 0.5 --k 1 --s2t-freq 0.5 --s2t-alpha 0 1 --t2s-freq 0.5 --t2s-alpha 0 1 --occlude-rate 0.5 --occlude-thresh 0.9 
#surreal to syrip without style decoder, with visibility, with kp encoder and with prior (PRDA)
#python train_human_to_infant.py '/data/AmitRoyChowdhury/dripta/surreal_processed' '/data/AmitRoyChowdhury/SyRIP/data/syrip/images' -s SURREAL -t SyRIP --target-train SyRIP_mt --log logs/surreal2sp_ta_mini/syn2mix_uda --prior '/data/AmitRoyChowdhury/sarosij/prior_data/MiniRGBD/ckpts/prior_stage_3.pt' --kp2seg '/data/AmitRoyChowdhury/sarosij/kp2seg_data/SURREAL_kp2seg_gan.pt' --resume 'checkpoints/surreal2sp_ta_mini/syn2mix_pre_free_pose_resnet101/checkpoints_2024-07-01-10_37_13/best_pt.pth' --debug --lambda_c 1 --lambda_s 1e-6 --lambda_p 1e-6 --mode 'baseline' --rotation_stu 60 --shear_stu -30 30 --translate_stu 0.05 0.05 --scale_stu 0.6 1.3 --color_stu 0.25 --blur_stu 0 --rotation_tea 60 --shear_tea -30 30 --translate_tea 0.05 0.05 --scale_tea 0.6 1.3 --color_tea 0.25 --blur_tea 0 -b 32 --mask-ratio 0.5 --k 1 --s2t-freq 0.5 --s2t-alpha 0 1 --t2s-freq 0.5 --t2s-alpha 0 1 --occlude-rate 0.5 --occlude-thresh 0.9
#python train_human_to_infant.py '/data/AmitRoyChowdhury/dripta/surreal_processed' '/data/AmitRoyChowdhury/SyRIP/data/syrip/images' -s SURREAL -t SyRIP --target-train SyRIP_mt --log logs/surreal2sp_p3s2r/syn2syn_prior --prior '/data/AmitRoyChowdhury/SyRIP/SyRIP_data_split/300S/prior/prior_stage_3.pt' --kp2seg '/data/AmitRoyChowdhury/sarosij/kp2seg_data/SURREAL_kp2seg_gan.pt' --debug --lambda_c 1 --pretrain-epoch 1 --lambda_s 1e-6 --lambda_p 1e-6 --mode 'all' --rotation_stu 60 --shear_stu -30 30 --translate_stu 0.05 0.05 --scale_stu 0.6 1.3 --color_stu 0.25 --blur_stu 0 --rotation_tea 60 --shear_tea -30 30 --translate_tea 0.05 0.05 --scale_tea 0.6 1.3 --color_tea 0.25 --blur_tea 0 -b 32 --mask-ratio 0.5 --k 1 --s2t-freq 0.5 --s2t-alpha 0 1 --t2s-freq 0.5 --t2s-alpha 0 1 --occlude-rate 0.5 --occlude-thresh 0.9

#FiDIP Comparison
#minirgbd to syrip (baseline - udape)
#python train_human_to_infant.py '/data/AmitRoyChowdhury/MINI-RGBD_web' '/data/AmitRoyChowdhury/SyRIP/data/syrip/images' -s MiniRGBD -t SyRIP --target-train SyRIP_mt --log logs/mini2sp_baseline/syn2mix --debug --lambda_c 1 --pretrain-epoch 40 --mode 'baseline' --rotation_stu 60 --shear_stu -30 30 --translate_stu 0.05 0.05 --scale_stu 0.6 1.3 --color_stu 0.25 --blur_stu 0 --rotation_tea 60 --shear_tea -30 30 --translate_tea 0.05 0.05 --scale_tea 0.6 1.3 --color_tea 0.25 --blur_tea 0 -b 32 --mask-ratio 0.5 --k 1 --s2t-freq 0.5 --s2t-alpha 0 1 --t2s-freq 0.5 --t2s-alpha 0 1 --occlude-rate 0.5 --occlude-thresh 0.9
#minirgbd to syrip (baseline + prior)
#python train_human_to_infant.py '/data/AmitRoyChowdhury/MINI-RGBD_web' '/data/AmitRoyChowdhury/SyRIP/data/syrip/images' -s MiniRGBD -t SyRIP --target-train SyRIP_mt --log logs/mini2sp_baseline_prior/syn2mix --debug --lambda_c 1 --resume 'checkpoints/mini2sp_baseline/syn2mix_pose_resnet101/checkpoints_2024-07-09-13_12_09/best_pt.pth' --prior '/data/AmitRoyChowdhury/sarosij/prior_data/MiniRGBD/ckpts/prior_stage_3.pt' --mode 'prior' --rotation_stu 60 --shear_stu -30 30 --translate_stu 0.05 0.05 --scale_stu 0.6 1.3 --color_stu 0.25 --blur_stu 0 --rotation_tea 60 --shear_tea -30 30 --translate_tea 0.05 0.05 --scale_tea 0.6 1.3 --color_tea 0.25 --blur_tea 0 -b 32 --mask-ratio 0.5 --k 1 --s2t-freq 0.5 --s2t-alpha 0 1 --t2s-freq 0.5 --t2s-alpha 0 1 --occlude-rate 0.5 --occlude-thresh 0.9
#minirgbd to syrip (baseline + prior)
#python train_human_to_infant.py '/data/AmitRoyChowdhury/MINI-RGBD_web' '/data/AmitRoyChowdhury/SyRIP/data/syrip/images' -s MiniRGBD -t SyRIP --target-train SyRIP_mt --log logs/mini2sp_all/syn2mix --debug --lambda_c 1 --lambda_p 1e-6 --lambda_s 1e-5 --pretrain-epoch 40 --prior '/data/AmitRoyChowdhury/sarosij/prior_data/MiniRGBD/ckpts/prior_stage_3.pt' --kp2seg '/data/AmitRoyChowdhury/sarosij/kp2seg_data/SURREAL_kp2seg_gan.pt' --mode 'all' --rotation_stu 60 --shear_stu -30 30 --translate_stu 0.05 0.05 --scale_stu 0.6 1.3 --color_stu 0.25 --blur_stu 0 --rotation_tea 60 --shear_tea -30 30 --translate_tea 0.05 0.05 --scale_tea 0.6 1.3 --color_tea 0.25 --blur_tea 0 -b 32 --mask-ratio 0.5 --k 1 --s2t-freq 0.5 --s2t-alpha 0 1 --t2s-freq 0.5 --t2s-alpha 0 1 --occlude-rate 0.5 --occlude-thresh 0.9

#syrip to minirgbd (pisa)
python train_human_to_infant.py '/data/AmitRoyChowdhury/SyRIP/data/syrip/images' '/data/AmitRoyChowdhury/MINI-RGBD_web' -s SyRIP -t MiniRGBD --target-train MiniRGBD_mt --log logs/rough/mix2syn --debug --lambda_c 1 --lambda_p 1e-6 --lambda_s 1e-5 --pretrain-epoch 40 --prior '/data/AmitRoyChowdhury/sarosij/prior_data/SyRIP/ckpts/all/prior_stage_3.pt' --kp2seg '/data/AmitRoyChowdhury/sarosij/kp2seg_data/SURREAL_kp2seg_gan.pt' --mode 'all' --rotation_stu 60 --shear_stu -30 30 --translate_stu 0.05 0.05 --scale_stu 0.6 1.3 --color_stu 0.25 --blur_stu 0 --rotation_tea 60 --shear_tea -30 30 --translate_tea 0.05 0.05 --scale_tea 0.6 1.3 --color_tea 0.25 --blur_tea 0 -b 32 --mask-ratio 0.5 --k 1 --s2t-freq 0.5 --s2t-alpha 0 1 --t2s-freq 0.5 --t2s-alpha 0 1 --occlude-rate 0.5 --occlude-thresh 0.9

#syrip to syrip (pisa)
#python train_human_to_infant.py '/data/AmitRoyChowdhury/SyRIP/data/syrip/images' '/data/AmitRoyChowdhury/SyRIP/data/syrip/images' -s SyRIP -t SyRIP --target-train SyRIP_mt --log logs/sp2sp_fidip/mix2mix --debug --lambda_c 1 --pretrain-epoch 40 --prior '/data/AmitRoyChowdhury/sarosij/prior_data/MiniRGBD/ckpts/prior_stage_3.pt' --kp2seg '/data/AmitRoyChowdhury/sarosij/kp2seg_data/SURREAL_kp2seg_gan.pt' --mode 'all' --rotation_stu 60 --shear_stu -30 30 --translate_stu 0.05 0.05 --scale_stu 0.6 1.3 --color_stu 0.25 --blur_stu 0 --rotation_tea 60 --shear_tea -30 30 --translate_tea 0.05 0.05 --scale_tea 0.6 1.3 --color_tea 0.25 --blur_tea 0 -b 32 --mask-ratio 0.5 --k 1 --s2t-freq 0.5 --s2t-alpha 0 1 --t2s-freq 0.5 --t2s-alpha 0 1 --occlude-rate 0.5 --occlude-thresh 0.9